### PR TITLE
sometimes the observables are screwed probably due to race condition…

### PR DESCRIPTION
**Pull request by andypetrella**
probably between Observable.start and makeObservable (called in javascript in cells).

It's hard to tell and reproduce systematically (given the problem) but looks like the problem is well narrowed.
However, the fix might not be enough, then we'll need to detect:
* why the Observable.start hasn't been called
* call it if not...

### CODE REVIEW

**Comment by vidma** [comment]
what are the consequences of this problem with observables?

**Comment by andypetrella** [comment]
the dataframe aren't rendered (only the header), or simply all reactive components aren't just showing anything because their aren't connected :-S

**Comment by vidma** [comment]
and does this PR seem to fix the problem?

**Comment by andypetrella** [comment]
I can't reproduce the problem systematically, but at least it puts some barriers, and gives more info in logs to allow us narrowing the real cause (and thus reproducing it systematically)

**Comment by vidma** [comment]
just been unable to run code again (different issue), this: ```Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.notify_dom_change @ observable.js:167(anonymous function) @ observable.js:188
```

closing tab & reopening seemingly fixed it. refresh didn't work.

**Comment by vidma** [comment]
we're seeing damn random instability on slightly larger jobs:
- progressbar would not always show up
- cells sometimes are impossible to run (seeing mainly `kernel_ready` and no other log messages)

did you kinda test this code? If so, I could compile and run on our cluster hoping it to improve.

**Comment by andypetrella** [comment]
In the #416 I see the rendering problem happening regularly, and the way to solve that is to call `require(["observable"], function(O) {O.start()})` which this PR is not really forcing.

I'll merge this PR into #416 first to see if it clears out the problem, if not where I can force the `start()` of `Observable`.

**Comment by vidma** [comment]
so our notebooks now run with this merged in. so far didn't notice anything new to be broken.

* left a notebook open for an hour or so
* reran a codecell `PivotChart(someDataframe, maxPoints=2500)`
* code got executed and printed out:
```
res19: notebook.front.widgets.PivotChart[org.apache.spark.sql.DataFrame] = <PivotChart widget>
```
* howerver no chart is shown, and console shows:
```
mimebundle missing metadata Object
:9000/assets/javascripts/notebook/observable.js:121 Delaying the creation of Observable (anon351011d2579f06529067dce4ee3c6a08,observableArray,) since Observable isn't initialized yet
:9000/assets/javascripts/notebook/observable.js:122 Observable not initialized: Object
:9000/assets/javascripts/notebook/observable.js:121 Delaying the creation of Observable (anon89af9e2c0d25bb04e4a02f1d52b569ca,observable,) since Observable isn't initialized yet
:9000/assets/javascripts/notebook/observable.js:122 Observable not initialized: Object
Chart%20Examples1.snb:8 Uncaught TypeError: Cannot read property 'extend' of undefined
:9000/assets/javascripts/notebook/observable.js:121 Delaying the creation of Observable (anoncf1df0b62e35c5ec6cdb42bd4ccd8e01,observable,) since Observable isn't initialized yet
:9000/assets/javascripts/notebook/observable.js:122 Observable not initialized: Object
:9000/assets/javascripts/notebook/observable.js:121 Delaying the creation of Observable (anonefbe7fe1cddbefaf77325a1dc00a0fc6,observable,) since Observable isn't initialized yet
:9000/assets/javascripts/notebook/observable.js:122 Observable not initialized: Object
:9000/assets//javascripts/notebook/magic/pivotChart.js:76 Uncaught TypeError: Cannot read property 'subscribe' of undefined
```

**Comment by vidma** [comment]
might need some more love, but can be done in separate PR (don't seem to be worse than before). 
so merging this to make deployments simpler.

**Comment by vidma** [comment]
I'm afraid this PR might be messing up the PivotChart sometimes, as we've seen in lazy kernel start...

**Pull request merged**
