### PR TITLE
Update play to 2.3.10. Previous version not available in Maven centra…

### PR DESCRIPTION
**Pull request by meh-ninja**
…l anymore.
@andypetrella @vidma 
Updating to the most recent version of play 2.3.

### CODE REVIEW

**Comment by meh-ninja** [comment]
But why a previously merged pr is appearing here?

**Comment by meh-ninja** [comment]
Failing test, looking into this.

**Comment by vidma** [comment]
> But why a previously merged pr is appearing here?

you  might need our old friend 
```bash
git checkout master
git pull origin master
git checkout - # back to your branch
git rebase master
```

**Comment by meh-ninja** [comment]
it was a clear clone. That's what's interesting.

**Pull request merged**
