### PR TITLE
Upgrade to latest version of Play (2.4.2).

### PR DESCRIPTION
**Pull request by cheleb**
Hi,
  I've just upgraded version, naïvely fixed the compilations error.
  I had to override version of jackson and common codec.
Thank you so much for this project.
HIH

### CODE REVIEW

**Comment by andypetrella** [comment]
Hey @cheleb , thanks for everything: the PR and the kind words!

If I may ask, I do have some questions ^^:

* what do you think will bring 2.4 to the plate → I'm just wondering and interested to know, specially based on gossip I caught on certain choices taken in 2.4. Don't get me wrong I'm not against an upstep ;-)
* the library clashes is the hardest thing I had to manage when including spark with play. Specially the akka compatibility. Did you tried some code in a small cluster to see if it's still okay? If not we can plan something of course

I just want to be sure we won't break something, and to know that, it's not easy, because the environment is hostile to tests (we really need some integration tests actually, it'd be so lovely ^^).

thanks again!
andy

PS: you work(ed?) at geomatys ? ;-)

**Comment by cheleb** [comment]
Hi Andy,
  You're more than welcome !!!
  To be frank, latest and greatest was my first motivation :)
  BTW the 2.4 comes with long waited DI (guice) mechanism.
  About akka AFAIK play depends on 2.3.
I will make some test asap.

PS: Yep I work*ed *at Geomatys, I've resign to join tabmo.fr (in few month)
for an a more Data oriented job (hence my interest for this project :) )
PS2: You know (coworker) Frederic Houbie ?

On Wed, Jul 22, 2015 at 10:12 PM, Andy Petrella <notifications@github.com>
wrote:

> Hey @cheleb <https://github.com/cheleb> , thanks for everything: the PR
> and the kind words!
>
> If I may ask, I do have some questions ^^:
>
>    - what do you think will bring 2.4 to the plate → I'm just wondering
>    and interested to know, specially based on gossip I caught on certain
>    choices taken in 2.4. Don't get me wrong I'm not against an upstep ;-)
>    - the library clashes is the hardest thing I had to manage when
>    including spark with play. Specially the akka compatibility. Did you tried
>    some code in a small cluster to see if it's still okay? If not we can plan
>    something of course
>
> I just want to be sure we won't break something, and to know that, it's
> not easy, because the environment is hostile to tests (we really need some
> integration tests actually, it'd be so lovely ^^).
>
> thanks again!
> andy
>
> PS: you work(ed?) at geomatys ? ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/pull/275#issuecomment-123848819>
> .
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by andypetrella** [comment]
Hey, sounds good, I dunno if this way of doing DI (or DI in general is finally something interesting to have, I have a personal idea on that, but nah).
Anyway, switching to new versions should also mean better perf and less bugs, so I'm for it.
As you said, and it's very gentle to do some, we need to test first how this will behave in a cluster environment.

PS: okay, that's cool -- I don't know tabmo.fr, let me know if you need some help for having the spark notebook running there! I'll be very happy to add their info in the README page  then ;-)
PS2: I worked with him ~6 years Ionic>Erdas>Intergraph ^^

**Comment by cheleb** [comment]
Hi Andy,
  I will try this week end to test the cluster with the latest version of
play. A local (AKA same host) cluster is enough ?
Thx


On Sun, Jul 26, 2015 at 2:40 PM, Andy Petrella <notifications@github.com>
wrote:

> Hey, sounds good, I dunno if this way of doing DI (or DI in general is
> finally something interesting to have, I have a personal idea on that, but
> nah).
> Anyway, switching to new versions should also mean better perf and less
> bugs, so I'm for it.
> As you said, and it's very gentle to do some, we need to test first how
> this will behave in a cluster environment.
>
> PS: okay, that's cool -- I don't know tabmo.fr, let me know if you need
> some help for having the spark notebook running there! I'll be very happy
> to add their info in the README page then ;-)
> PS2: I worked with him ~6 years Ionic>Erdas>Intergraph ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/pull/275#issuecomment-124977560>
> .
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by andypetrella** [comment]
@cheleb super cool. Normally standalone will be just fine. Actually the problem will mainly come with dependencies clash and akka binary compat.
It'll be worth also trying on yarn (after your test I'll test on EMR for that if you like)

wdyt?

**Comment by cheleb** [comment]
Hi Andy,
  Hope you're (g|d)oing well!
  I soon as I can, I will follow
https://www.youtube.com/watch?v=iW25_dR_9EE&list=TL7OR_N42ushkyNTA5MjAxNQ
to test the notebook in cluster environment.
Cheers,
Olivier


On Fri, Aug 7, 2015 at 6:30 PM, Andy Petrella <notifications@github.com>
wrote:

> @cheleb <https://github.com/cheleb> super cool. Normally standalone will
> be just fine. Actually the problem will mainly come with dependencies clash
> and akka binary compat.
> It'll be worth also trying on yarn (after your test I'll test on EMR for
> that if you like)
>
> wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/pull/275#issuecomment-128757486>
> .
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by andypetrella** [comment]
Hey Olivier,

This would be nice indeed, however, if you're mentioning the upset of play,
I've seen some stuffs about akka 2.4 that would break it.

Anyway, trying the notebook in a cluster is more than good! Enjoy.
Although, Samklr reported me some issues with DCOS that I'll fix before
October :-).

Have fun!

cheers
andy


On Fri, Sep 25, 2015 at 5:17 PM NOUGUIER Olivier <notifications@github.com>
wrote:

> Hi Andy,
> Hope you're (g|d)oing well!
> I soon as I can, I will follow
> https://www.youtube.com/watch?v=iW25_dR_9EE&list=TL7OR_N42ushkyNTA5MjAxNQ
> to test the notebook in cluster environment.
> Cheers,
> Olivier
>
>
> On Fri, Aug 7, 2015 at 6:30 PM, Andy Petrella <notifications@github.com>
> wrote:
>
> > @cheleb <https://github.com/cheleb> super cool. Normally standalone will
> > be just fine. Actually the problem will mainly come with dependencies
> clash
> > and akka binary compat.
> > It'll be worth also trying on yarn (after your test I'll test on EMR for
> > that if you like)
> >
> > wdyt?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/andypetrella/spark-notebook/pull/275#issuecomment-128757486
> >
> > .
> >
>
>
>
> --
> "Computers are useless. They can only give you answers."
> - Pablo Picasso -
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/pull/275#issuecomment-143249835>
> .
>
-- 
andy

**Comment by andypetrella** [comment]
I think this is going to be easier when Spark will "get rid" of their akka stuff (which is plan for 1.6 or 1.7 can't remember)
So it'll be then a better time to try at that time probably :-S

**Comment by andypetrella** [comment]
this requires more that a alignment with the framework, but a more depth refactoring of the classpath management, let's tackle that in the future-master branch where work has started in order to support spark 2.0.0 for instance and also clean old stuff

**Pull request closed without merging**
