### PR TITLE
Cleaning plotting libs

### PR DESCRIPTION
**Pull request by andypetrella**
* removes plotting libs (plotly superseeds all of them): removed bokeh, tau and rickshaw
* adapt notebooks (removed `:dp` and other classpath stuff), adapted plotting
* restore Flow js (chrome removed one svg function needed by joint.js)

> This will save quite some time at loading (JS was huge, only even bokeh is a ton less)

cc @drewnoff

### CODE REVIEW

**Comment by andypetrella** [comment]
Yes integration reste like that are in mind head for months... :)

Git stuff: I believe you given that I don't know ^^

**Comment by vidma** [comment]
> Git stuff: I believe you given that I don't know ^^

cool. I'm sure you gonna like these commands. check this http://nuclearsquid.com/writings/git-add/ !

**Comment by andypetrella** [comment]
well TLDR :-)

We'll see next time, meanwhile I'll merge this since it's accepted and backport to old spark branch then

**Comment by vidma** [comment]
👍

**Pull request merged**
