### PR TITLE
added MyPerfectWeather.eu inspired notebook

### PR DESCRIPTION
**Pull request by radek1st**

### CODE REVIEW

**Comment by vidma** [comment]
could we have more specific file name? like `Data_analysis_at_MyPerfectWeather` (didn't look at the snb file contents).

also, it's certainly nice to see the output, but it's rather big - 3MB.

**Comment by andypetrella** [comment]
@radek1st yes! this is exciting.
Per @vidma comment, it would be great to have a more explicit name (even with spaces ^^), but the most important would be to clean the outputs so the file is smaller and then leave the user redoing it on his own.

thanks !!!!

**Comment by radek1st** [comment]
@vidma @andypetrella I've addressed the comments. Please let me know if you have any other comments or questions. Cheers

**Comment by andypetrella** [comment]
:fireworks: \o/

**Pull request merged**
