### PR TITLE
Improve the job progressbar

### PR DESCRIPTION
**Pull request by vidma**
screen shot 2015-11-26 at 15 32 02

P.S. it might slightly suck that the bars are still fully redrawn  on each status update, so hovering is not very nice until jobs complete (but there are logs, and spark UI too ...; it would be nice to provide a link to spark UI for advanced users)

@andypetrella

### CODE REVIEW

**Comment by vidma** [comment]
I'd say :rocket:

**Comment by vidma** [comment]
also IMHO it would make much sense to reset the progress-bar when rerunning all the actions, and maybe in some other cases. as currently it seem to accumulate as long as notebook is open.

**Comment by vidma** [comment]
- Reenabled global positioning
- Grouped completed jobs into one bar, so UI is faster and progress is meaningful with large number of stages

**Comment by andypetrella** [comment]
I guess that #399 will be shipped with this one right?

**Comment by vidma** [comment]
yeah. just merge this one, and I will rebase #399 .

**Pull request merged**
