### PR TITLE
anomaly detection notebook

### PR DESCRIPTION
**Pull request by radek1st**
TODO:

1) Change the initial data load to be from CSV and not JSON (I had it this way to show how easy it is, but it wasn't the original dataset)
2) Run K-Means with a seed, so there will be always at least one anomaly detected during the presentation
3) Rewrite LogStreamer in Scala :)
4) Welcome your feedback

### CODE REVIEW

**Comment by andypetrella** [comment]
Hey @radek1st 
This is really great stuffs!!! I've made some modifications wrt to data download and preparation + the scala version of the streamer.
You can test it out: https://github.com/andypetrella/spark-notebook/pull/194

I still have a problem with serialization atm, but I'll work on that crap asap

thanks A LOT for the hard and great work + share
cheers
andy

**Comment by radek1st** [comment]
Hi @andypetrella 

I tried setting a seed for the K-Means, but every time I run I got different results, so it doesn't work as I expected and we cannot make it reproducible this way...

Also, with the new version of the notebook, -mem option doesn't seem to be working anymore and it takes too long for the k-means to run on a local mode with the default memory. Do you know how can I increase the memory for the driver now?

Cheers,
Radek

**Comment by andypetrella** [comment]
Hey @radek1st 

How did you set the seed, using the spark api directly? K-Means is deterministic wrt the initial centroid, after that there won't be any random anymore.

For the `-mem`, it should still work actually, it's weird it doesn't on your box. When you launch it you should see some information in the logs for the server, and when you launch a notebook it's also printed in the command line in the related log file (there is one per session and notebook). Could you check there?

Cheers,
andy

**Comment by radek1st** [comment]
@andypetrella 

I've tried it like this:

val numIterations = 10 //in production it should be more
val K = 150
val runs = 1
val initializationMode = "k-means||"
val seed = 1234 //fixed in order to reproduce the results of prediction

val clusters = KMeans.train(data, K, numIterations, runs, initializationMode, seed)

**Comment by radek1st** [comment]
!! WARNING !! -mem option is ignored. Please use -J-Xmx and -J-Xms

and in Spark UI Executor memory doesn't change

**Pull request merged**
