### PR TITLE
Add a report presentation mode

### LINKED ISSUE #387: Toggle of cell output using shortcut keys does not reflect menu cell output toggle
Run some cell entries that output numbers 1-10
select some graph for the numbers to have graphical output
select the cell and then escpe out of edit mode but still on cell
select t/o for toggle output on / off as per help on keyboard shortcut
Expected: Toggle of the output
Actual: The output only partially is cleared. Graph and some output not clered.

Note:
Repeat the same steps above but toggle the output from the menu (Toggle Current output)
The menu toggle applies an elipse "..." to toggled sections, keyboard shortcuts do not.

To Fix: Allow keyboard to do the same as the menu options as that seems to work

Version: andypetrella/spark-notebook:0.6.2-SNAPSHOT-scala-2.11.6-spark-1.5.1-hadoop-2.2.0-with-parquet 

I checked for toggle/output in existing defects and did not find - excuse me if its a dupe or fixed already.

### PR DESCRIPTION
**Pull request by vidma**
**goal:** display only visual output (hide menus, headers, code, and progress-bar). verbose `stdout` should be hidden too (in our usecase).

-  existing fns for toggling input/output are not very helpful here, so use simple CSS to hide non needed elements (like in `media=print`)
- report mode also includes:
  * made width universal by using `container-fluid` (full-width)
  * first/selected cell should look the same
- Added menu entry for Report view

in some way, fixes #387 too..

### CODE REVIEW

**Comment by vidma** [comment]
@andypetrella

**Comment by andypetrella** [comment]
I checked the code ... using my eyes only ^^. I'm at an event I was keynoting... I will probably leave soon and try this out this evening or tomorrow morning → it looks very cool (the CSS is pretty elaborated, you must have loved doing that -- kidding ;-))

**Comment by vidma** [comment]
Few fixes, refactored with simpler CSS, and added menu entry for Report view.

**Comment by andypetrella** [comment]
tested and liked it... going to merge that!
Great job man

**Comment by andypetrella** [comment]
I merged another branch where I've quickly added the support of var env `${...}` in customLocalRepo → helpful to define: `${HOME}/.ivy2` :-D

**Pull request merged**
