### PR TITLE
[ #142] An early state suggestion for the usage of the Scala Presentation Compiler.

### PR DESCRIPTION
**Pull request by cbvoxel**
From our discussion in #142 and the dire need to take advantage of Scala's Presentation Compiler (PC) for a better user experience in the spark-notebook, this is my very first and naive suggestion. It "injects" iteself into the ReplCalculator by just replacing the object from the repl to the presentationCompiler. The PC has a complete method which does the following:
 1. wrap the code into an object snippet
 2. extract already written user code snippet, that should be completed
 3. calculate the TypeCompletion and filter via "contains" the result with the user code snippet
 4. if the TypeCompletion is empty, calculate ScopeCompletion and filter via "contains" the result with the user code snippet
 5. convert to Match and return

Cool:
It is a lot more fun to use this in the notebook. You can use "TAB" to call the PC. It really works a lot better than the REPL.

Drawbacks:
 1. Sorting is terrible: I don't do any, because honestly, I have not the slightest idea on what I should be sorting. I would like symbols to appear in the order of siginificance. But what is significane?
 2. Only the current cell is given to the PC. That means, that other information from other cells are simply ignored, and will not count into the completion. 
 3. Empty Line TAB really creates a TAB, lol! We should have a better way to invoke code completion.
 4. Imports aren't moved to the top and are embedded into the code. It is probably okay, but wouldn't it be nicer to have them on the top?
 5. Probably a lot more like exception handling... which is absent.

Cool to have: 
 1. Get Type Information, by hovering and holding Ctrl?
 2. Get Error Info when saving?
 3. Include all Cells for the call to the PC?
 4. Gather all Imports and put them to the top of the object snippet while counting the position correctly?

### CODE REVIEW

**Comment by andypetrella** [comment]
@cbvoxel this is a very good start, I'll soon git it a short try to see what we can do to integrate it. Since it replaces the regular completion it must at least provide the same as the original one (which I think it does).
Only by then I'll can try to answer your questions which are all relevant, and also see what we can do to overcome some drawbacks if we have to.

thanks for this awesome work!

Meanwhile, I'm adding @alexy who had some interests in this PR too!

Also @dragos who, I'm sure, can give some more hints (if he has time, because he's a very busy man ^^)

**Comment by cbvoxel** [comment]
Okay, I have forgotten a HUGE drawback of the old solution. It was that any symbols generated by the init scripts are completely ignored. 
I changed that, so that with each loading of the ReplCalculator, all init scripts are insterted into the PC.

Now we almost have the all that back what the REPL gives us...

...except one thing (as far as I know). I added dependencies (spark-csv) through :dp but the PC isn't aware of that. Why?

**Comment by cbvoxel** [comment]
Oh, and sorry for putting fix #326 into this PR. I don't know git so well as to handle this case, sorry...!

**Comment by andypetrella** [comment]
@cbvoxel no problem for several fix in one PRs (I'm not that freak on this kind of procedure ^^).

For `:dp`, it's weird and will need to take a closer look (but for now, it's really hard, I'm preparing and giving concurrently a 3 days training... it's fun and hard at the same time :D)

**Comment by dragos** [comment]
I think you should have a look at https://github.com/scala/scala/pull/4725/files which does exactly this, for the normal Scala REPL. Maybe this is all that needs to be done on the notebook side (use the new completer)! Note that it would correctly 'see' completions in from other cells.

**Comment by cbvoxel** [comment]
@dragos yes without looking into too much detail, this looks really cool! I'm glad you guys are doing this. 
As @andypetrella said in our previous discussion, this (awesome) addition will not be around for the scala version 2.10, or will it? I am asuming you are building your spark-notebook against the current master (or your fork) of scala. Do you think, we should therefore continue on this current PR approach, or is it unneccessary?

**Comment by andypetrella** [comment]
This is working like a charm! It's great that we can have this for 2.10.

WDYT, shouldn't we break this into several issues then?
Like we need to add that for scala 2.11.2 and 2.11.6 (2.11 versions used by spark so far).

And other issues for
*deal with multi cells (like take into account all upper cells?)
* handle function types definition (SHIFT+TAB)

@dragos any idea for 2.11 things?

**Comment by cbvoxel** [comment]
Okay @andypetrella ,
I have just commited a remedy to the "one cell only" completion. There are only minor changes to completer.js necessary, it work great now, and I am loving it. I hope that you had the chance to test it a bit.

As to your questions, it seems more concerning to @dragos as he knows a lot more about scala. But I guess, it is a "quick" fix to use this PR to enable richer autocompletion support. We are using it now and maybe there are some folks that would like this too.

As to the function types definition, I didn't mention, that when you have the cursor at a complete function name, then the PC spits out parameter definitions, e.g. if you have 
```
Seq(1,2,3).sortWith<= cursor position
```
you get (or are supposed to get)
```
Seq(1,2,3).sortWith(<lt:(Int, Int) => Boolean>)
```
It really is not working all the time :( 

Albeit that, I would like a better help by using (SHIFT+TAB) as you suppose. We would need another tooltip though. How would that work?

**Comment by dragos** [comment]
>
> Albeit that, I would like a better help by using (SHIFT+TAB) as you
> suppose. We would need another tooltip though. How would that work?
>
If you look at the branch I pointed to earlier, it's implemented there.

**Comment by cbvoxel** [comment]
Ah okay, I will have a look, thanks!

**Comment by andypetrella** [comment]
@dragos @cbvoxel cool :-), I'll test again this week end!! me happy

**Comment by andypetrella** [comment]
@cbvoxel man... I just tested it, and I understand why you love it, because this is TERRIBLE  !!!!
I love it soooo much.

Do you think we can port it to scala 2.11 easily? If not I'm okay to merge it asap and then create a ticket for each of those:
* scala 2.11 PC support
* shift + tab support (based on @dragos work)

how does that sounds for you guyz?

(I'll make a video of these stuffs, this is very very cool.)

**Comment by andypetrella** [comment]
You know what, I'm gonna integrate it.... lovin' it.

I've created #332 and #333 for the follow up on shift-tab and scala 2.11

**Comment by cbvoxel** [comment]
Hey @andypetrella, that's cool, thank you! 

I just realized, that my changes to the completer.js unfortunatly also affect scala 2.11 were there is no PC in effect. It should still work though ...

Also, why shouldn't the PC work with Scala 2.11?

WDYT about both?

**Pull request merged**
