### PR TITLE
Fix autocompletions for scala 2.11

### LINKED ISSUE #726: Fix Autocompletion for 2.11 :-(

### PR DESCRIPTION
**Pull request by vidma**
Activate PresentationCompiler for 2.11 (code based on 2.10 `ReplCalculator.scala`). 
fixes #726

long story:
- finally, `PresentationCompiler` seem to work with 2.11 as well (checked with Scala 2.11.8 with Spark 2.0).
- earlier in scala 2.11 autocompletions were not using `PresentationCompiler` at all (but some `repl.complete()`, and this one is now broken; PC was broken for 2.11 as I remember...).

P.S. I didn't notice any major issues, except for rarely weird completions (but I think we had this in 2.10 as well)...

@maasg @0asa 
cc @andypetrella

### CODE REVIEW

**Comment by andypetrella** [comment]
🆒  !!!
That's a huge improvement for the users, you are going to spread a wave of happiness and a bunch of 🌈 ;-)

**Comment by andypetrella** [comment]
fixes #798 #726 #709

**Comment by vidma** [comment]
didn't notice any concrete issues yet, but to have in mind that:
- `PresentationCompiler (PC)` used to be not very stable (including its tests @ Travis)
- auto-completions might block other commands within REPL (interrupt, cell-interrupt, enqueue cell execution)

**Comment by andypetrella** [comment]
@vidma this is only for spark2 ATM right? Can we pick it pre 2 branch as well?

**Comment by vidma** [comment]
> @vidma this is only for spark2 ATM right? Can we pick it pre 2 branch as well?

 already [did that for 1.6branch, tested with spark 1.6.3 on 2.11, seems OK](https://github.com/andypetrella/spark-notebook/commit/6bab453e8c23062cea2502040c15dc78e530e935)

**Comment by andypetrella** [comment]
woooo my bad :-)
awesome

**Pull request merged**
