### PR TITLE
added ammonite console REPL

### PR DESCRIPTION
**Pull request by antonkulaga**
I added [ammonite-REPL](http://lihaoyi.github.io/Ammonite/) as it is much-much better than scala-s default one and it allows to do some advanced staff, like loading dependencies from scala-console and running shell commands in an easy way.

### CODE REVIEW

**Comment by antonkulaga** [comment]
I also deleted redundant imports of typesafe-releases repo as 1) it moved to bintray 2) latest sbt imports type-safe releases by default

**Comment by andypetrella** [comment]
hey @antonkulaga thanks for the PR, I just had a lil time to check it out. Indeed, the REPL is better and I'm not against having it.

However, this adds the below dependencies to the runtime, which I'd like to avoid because we can have a lot of clashes out there (like ivy and jline for instance).

And in a sense, they are just necessary for the sbt console, since we don't use it elsewhere.

So, could you have a look how this deps on ammonite can be scoped to only the console classpath please?

Thanks a lot man

```
[info]   +-com.lihaoyi:ammonite-repl_2.10.4:0.4.5 [S]
[info]   | +-com.github.scopt:scopt_2.10:3.3.0 [S]
[info]   | +-com.lihaoyi:ammonite-ops_2.10:0.4.5 [S]
[info]   | | +-com.lihaoyi:pprint_2.10:0.3.4 (evicted by: 0.3.5)
[info]   | | +-com.lihaoyi:pprint_2.10:0.3.5 [S]
[info]   | | | +-com.lihaoyi:derive_2.10:0.3.5 [S]
[info]   | | | 
[info]   | | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | |   
[info]   | +-com.lihaoyi:ammonite-terminal_2.10:0.4.5 [S]
[info]   | | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | |   
[info]   | +-com.lihaoyi:pprint_2.10:0.3.5 [S]
[info]   | | +-com.lihaoyi:derive_2.10:0.3.5 [S]
[info]   | | 
[info]   | +-com.lihaoyi:scalaparse_2.10:0.2.1 [S]
[info]   | | +-com.lihaoyi:fastparse_2.10:0.2.1 [S]
[info]   | | | +-com.lihaoyi:fastparse-utils_2.10:0.2.1 [S]
[info]   | | | | +-org.scalamacros:quasiquotes_2.10:2.0.0 [S] (evicted by: 2.0.1)
[info]   | | | | | +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | | | | 
[info]   | | | | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   | | | |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | | |   
[info]   | | | +-org.scalamacros:quasiquotes_2.10:2.0.0 [S] (evicted by: 2.0.1)
[info]   | | | | +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | | | 
[info]   | | | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   | | |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | |   
[info]   | | +-org.scalamacros:quasiquotes_2.10:2.0.0 [S] (evicted by: 2.0.1)
[info]   | | | +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | | 
[info]   | | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | |   
[info]   | +-com.lihaoyi:upickle_2.10:0.3.5 [S]
[info]   | | +-com.lihaoyi:derive_2.10:0.3.5 [S]
[info]   | | +-org.spire-math:jawn-parser_2.10:0.7.0 [S]
[info]   | | 
[info]   | +-jline:jline:2.12
[info]   | +-org.apache.ivy:ivy:2.4.0
[info]   | +-org.scala-lang:scala-compiler:2.10.4 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | | 
[info]   | +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   | +-org.scalamacros:quasiquotes_2.10:2.0.1 [S]
[info]   |   +-org.scala-lang:scala-reflect:2.10.4 [S]
[info]   |   
```

**Comment by antonkulaga** [comment]
The simpliest thing to do is to add ammonite to another scope (test scope for instance, so it will work only for Console in test).

**Comment by andypetrella** [comment]
@antonkulaga I think you're right!

**Comment by antonkulaga** [comment]
I think @alexarchambault has the solution, he has just updated [sbt-ammonite](https://github.com/alexarchambault/sbt-ammonite) so it will be possible to use ammonite as sbt-plugin

**Comment by andypetrella** [comment]
indeed, again not against ammonite integration, but I never use the REPL
since I have the notebooks :),in a sense it's a counter sense since the
notebook is there to get rid on REPL.
So it must be lightweight and without side effect.
maybe the plug-in will put the deps still, so please check the different
classpath before :).

you know what I'd like also to have a bit of an highlight which use cases
would require the repl in the notebook project. thanks

Le mer. 19 août 2015 19:17, Anton Kulaga <notifications@github.com> a
écrit :

> I think @alexarchambault <https://github.com/alexarchambault> has the
> solution, he has just updated sbt-ammonite
> <https://github.com/alexarchambault/sbt-ammonite> so it will be possible
> to use ammonite as sbt-plugin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/pull/289#issuecomment-132853271>
> .
>
-- 
andy

**Comment by vidma** [comment]
let's close this.

**Pull request closed without merging**
