### PR TITLE
Intelligent auto-completions

### LINKED ISSUE #445: show fn description & param info on autocompletions (Tab)
P.S. we already have better autocompletion than databricks-notebook. they only list method names.
here, if entered a full method name, it shoulds the method signature (params).

cc @andypetrella

### PR DESCRIPTION
**Pull request by vidma**
this completer need a bit more love and refactoring but lets start simple.

- [x] basis for complex completions where text and completion value could differ, so `Match. toJsonWithDescription` gives a dict with:
  * `value` (the replacement to be put in code)
  * `display_text` - complete method signature, e.g. `method_name(params...): return_type` shown only in dropdown
- [x] format method signatures more naturally: 
  *  `method_name(param1: paramType, param2: paramType)`
- [x] always show all matching versions of a method/member including its return type:
  * i.e. `method_name(params...): return_type`
- [x] update tests

this gives much more advanced auto-comletions than in databricks-notebooks, hurray :tada: :balloon: 

in future we could show the docstrings if they exist. this would need some fancy tooltip box.

---

* data member completions, show ALL versions of a method with a full signature:
  - also, this do not add `()` anymore when parameters are empty, as it matches are not `methods` necessarily 

screen shot 2015-12-17 at 12 34 47

* selecting a match:
screen shot 2015-12-16 at 18 28 38

fixes #445

### CODE REVIEW

**Comment by vidma** [comment]
@andypetrella

**Comment by andypetrella** [comment]
this has astonished me  →  Waouw !
great job dude

**Comment by vidma** [comment]
yeah, but remember this swamp will need some more cleanup ;)

**Comment by andypetrella** [comment]
sure! but anyway → so cool

**Comment by vidma** [comment]
and regarding `autocompletion` maybe we should simply display all versions of a method straight away all the time, e.g.?
I type `System.getPr`, it should return:
- System.getProperties()
- System.getProperty(key: Str)
- System.getProperty(key: Str, def: Str)

instead of (as done now):
- System.getProperties()
- System.getProperty(key: Str) [multiple versions]

it might be more versbose in case of horriblish 22 versions of signatures, but Intellij don't do any fancy filtering, and then the behaviour would be more predictable and code would be a bit simpler :0

**Comment by vidma** [comment]
redone it to simply list all version of each method, so no `[multiple versions]`.

so should be kinda :ship:'able.

**Comment by andypetrella** [comment]
I'll give it a try
But still have to fix the tests :'(
Or change them? Or revamp them ... or ...

**Comment by andypetrella** [comment]
this is perfect to :ship: IMHO
@vidma do you have something else in mind to add to this astonished one?

**Comment by vidma** [comment]
only this: in future we could show the docstrings if they exist. this would need some fancy tooltip box.
but too complex for now (and docstrings might not be always available).

so :rocket:

**Pull request merged**
