### PR TITLE
new proposal for the skiny cp

### PR DESCRIPTION
**Pull request by andypetrella**
Hello @cbvoxel,

I made some adaptation to your [PR](https://github.com/andypetrella/spark-notebook/pull/283), mainly related to the cp building. 
I kept the original stuffs in the fork because it is using a variable env, and I think it doesn't matter for either win or unix the length of such var.

However, I changed both script bat and bash to use `lib/*` or `lib\*` + hadoop and extra cp.

Would you help me and me a check with this version to see if it solves or initial proble? Please :D.

THX and sorry for the delay.

andy

### CODE REVIEW

**Comment by cbvoxel** [comment]
Hello @andypetrella,

now it's my turn to apologize! Sorry, I have been busy with other stuff, but I have started looking into this. I hope to give a full report tomorrow, but we'll see how that works out.

One thing though: I think you are right that you keep the original stuff in the fork right there where it is. It is in the env variable (as you said) and probably gets cast into a classpath.jar via spark/yarn or so later on anyway. So it shouldn't really matter.

As for the other changes, I first have to get my Windows environment back up running. I have been fiddling around with it lately and now its broken, how sad... :(

Have a great evening, cheers,

Carsten

**Comment by andypetrella** [comment]
hehe @cbvoxel no problemo; take your time to test it. Take it easy.

cheers

**Comment by andypetrella** [comment]
Hehe no problemo,

Take it easy ;-)

**Comment by cbvoxel** [comment]
Hey @andypetrella,

yes, it works great! I must admit, that I don't really understand the concept but then again, little do I know about scala and especially SBT. I will review again, but right now, as usually, I have more pressing matters... 
So please merge your changes, that would be awesome.

BTW, spark notebook really rocks. I introduced it to my client who uses it now to work on the hadoop cluster. The only thing that I really really miss with spark-notebook is a great autocompletion. I know, you take that from the REPL, but it isn't good enough to really make it an awesome powertool. I usually have an IntelliJ open next to it to help me get what I want quicker. If someone was to take on the issue, what basic idea should be gone after?

Again thanks a lot for your great help with this issue, I really wanted to use spark-notebook and now that it's working, it's great!

**Comment by andypetrella** [comment]
Super cool man! Thanks a LOT.

For the completion, we'll work on that, here is [the issue](https://github.com/andypetrella/spark-notebook/issues/142) and we need to discuss with @dragos how we can move forward for the next versions... there is a lot of cleaning that can be done in the REPL stuffs that might be required before.

Before that, what I tend to do to see the type of a function, I execute:
```scala
myObject.aFunction _
```

Which gives me a `PartialFunction` and thus gives me the In/Out type :-)

**Comment by andypetrella** [comment]
this is closing https://github.com/andypetrella/spark-notebook/pull/283 too

**Pull request merged**
